spring.application.name=db-scripts
server.servlet.context-path=/db-scripts
server.port=8081

spring.datasource.logistic-db.platform=postgres
spring.datasource.logistic-db.jdbc-url=jdbc:postgresql://${LOGISTIC_DB_HOST:localhost}:5432/${LOGISTIC_DB_NAME:logistic_db}?currentSchema=${LOGISTIC_DB_SCHEMA:dev}
spring.datasource.logistic-db.username=${LOGISTIC_DB_USERNAME:postgres}
spring.datasource.logistic-db.password=${LOGISTIC_DB_PW:root}
spring.datasource.logistic-db.driver-class-name=org.postgresql.Driver
spring.datasource.logistic-db.liquibase.change-log=classpath:/db/changelog/logistic-db/db.changelog-logistic-db-v1.sql
